# Generated by Django 4.1.5 on 2023-01-11 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("addresses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bedrooms", models.IntegerField()),
                ("rooms", models.IntegerField()),
                ("suits", models.IntegerField()),
                ("kitchens", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
                ("toilets", models.IntegerField()),
                ("land_area", models.IntegerField()),
                ("parking_spaces", models.IntegerField()),
                ("sell_price", models.FloatField()),
                ("location_price", models.FloatField()),
                ("description", models.CharField(max_length=250)),
                ("is_available", models.BooleanField()),
                ("user_id", models.IntegerField()),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="addresses.address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SellHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_house",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="house_sold",
                        to="houses.house",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_at", models.DateField()),
                ("finish_at", models.DateField()),
                ("owner_id", models.IntegerField()),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="house_rented",
                        to="houses.house",
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renter_house",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="house",
            name="buyers",
            field=models.ManyToManyField(
                related_name="buyed_houses",
                through="houses.SellHouse",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="renters",
            field=models.ManyToManyField(
                related_name="rented_houses",
                through="houses.LocationHouse",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
