# Generated by Django 4.1.5 on 2023-01-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bedrooms", models.IntegerField()),
                ("rooms", models.IntegerField()),
                ("suits", models.IntegerField()),
                ("kitchens", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
                ("toilets", models.IntegerField()),
                ("land_area", models.IntegerField()),
                ("parking_spaces", models.IntegerField()),
                ("sell_price", models.FloatField()),
                ("location_price", models.FloatField()),
                ("description", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="LocationHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_at", models.DateField()),
                ("finish_at", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="SellHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
