# Generated by Django 4.1.5 on 2023-01-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationhouse",
            name="location_price",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sellhouse",
            name="owner_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sellhouse",
            name="sell_price",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
