# Generated by Django 4.1.5 on 2023-01-10 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("addresses", "0001_initial"),
        ("houses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sellhouse",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_house",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sellhouse",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="house_sold",
                to="houses.house",
            ),
        ),
        migrations.AddField(
            model_name="locationhouse",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="house_rented",
                to="houses.house",
            ),
        ),
        migrations.AddField(
            model_name="locationhouse",
            name="renter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="renter_house",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="addresses.address",
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="buyers",
            field=models.ManyToManyField(
                related_name="buyed_houses",
                through="houses.SellHouse",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="renters",
            field=models.ManyToManyField(
                related_name="rented_houses",
                through="houses.LocationHouse",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
