# Generated by Django 4.1.5 on 2023-01-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0004_remove_house_user_house_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house",
            name="renters",
        ),
        migrations.RemoveField(
            model_name="locationhouse",
            name="house",
        ),
    ]
