# Generated by Django 4.1.5 on 2023-01-05 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("houses", "0005_remove_house_renters_remove_locationhouse_house"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="renters",
            field=models.ManyToManyField(
                related_name="rented_houses",
                through="houses.LocationHouse",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="locationhouse",
            name="house",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="house_rented",
                to="houses.house",
            ),
            preserve_default=False,
        ),
    ]
