# Generated by Django 4.1.5 on 2023-01-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0006_house_renters_locationhouse_house"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationhouse",
            name="owner_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
