# Generated by Django 4.1.5 on 2023-01-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="user_id",
            field=models.IntegerField(default=0),
        ),
    ]
