# Generated by Django 4.1.5 on 2023-01-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_alter_comments_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="user_id",
            field=models.IntegerField(default=0),
        ),
    ]
